[build-system]
requires = ["setuptools>=68", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "eubar"
dynamic = ["version"]
description = "Regression-based toolkit for modeling sequence effects on transcription factor binding using accessible chromatin as probes"
readme = "README.md"
requires-python = ">=3.12"

authors = [
  { name = "Eftyhios (Aki) Kirbizakis" },
  { name = "Swenke Bailey" }
]

license = { text = "GNU General Public License v3.0" }

dependencies = [
  "matplotlib>=3.8",
  "numpy>=1.26",
  "pandas>=2.1",
  "pybedtools>=0.12",
  "pyfaidx>=0.8",
  "statsmodels>=0.14",
  "pyBigWig>=0.3.22",
  "numba>=0.59",
  "scipy>=1.11",
  "PyYAML>=6",
  "logomaker>=0.8"
]

[project.optional-dependencies]
test = [
  "pytest>=7"
]

[project.scripts]
eubar = "eubar.cli:main"

[project.urls]
Repository = "https://github.com/SvenBaileyLab/EUbar"

[tool.setuptools.packages.find]
include = ["eubar*"]

[tool.setuptools_scm]